### ISSUE TITLE
Graph data is unreliable

### ISSUE THREAD

**Issue by ghost** [comp500/sensor-reporter#4]
Data for the graphs at the bottom of the main page sometimes is out of data or includes anomalous data. In addition, sometimes there are 20 datapoints that are not 5 minutes apart

**Comment by comp500** [comment]
TODO: query newest (20 * 5) measurements, average them to get averages over every 5 minutes
Therefore we can get accurate averages for the past (20 * 5) minutes, apart from pressure where we might want longer timings

**Comment by ghost** [comment]
is this done?

**Comment by comp500** [comment]
possibly, i don't know

**Comment by ghost** [comment]
Graphing data fixed with merge of dynamicsensors
